// Global test setup for Vitest
// - Adds jest-dom matchers (e.g., toBeInTheDocument)
// - Can host other global test config/mocks later
import "@testing-library/jest-dom/vitest";
import { vi } from "vitest";
import React from "react";
// Load global styles so getComputedStyle in JSDOM sees our Tailwind utilities and tokens
import "../index.css";

// Mock lucide-react dynamic imports to prevent window undefined errors in tests
vi.mock("lucide-react/dist/esm/dynamicIconImports.js", () => ({
  default: {
    // Mock all the icons used in ModularIcon - return a simple SVG component for testing
    menu: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'menu-icon' }) })),
    x: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'x-icon' }) })),
    plus: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'plus-icon' }) })),
    "plus-circle": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'plus-circle-icon' }) })),
    minus: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'minus-icon' }) })),
    "edit-3": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'edit-icon' }) })),
    "trash-2": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'delete-icon' }) })),
    check: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'check-icon' }) })),
    "alert-triangle": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'warning-icon' }) })),
    "alert-circle": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'error-icon' }) })),
    info: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'info-icon' }) })),
    tag: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'tag-icon' }) })),
    calendar: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'calendar-icon' }) })),
    clock: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'clock-icon' }) })),
    users: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'users-icon' }) })),
    user: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'user-icon' }) })),
    "user-plus": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'user-plus-icon' }) })),
    target: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'target-icon' }) })),
    trophy: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'trophy-icon' }) })),
    award: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'award-icon' }) })),
    star: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'star-icon' }) })),
    "trending-up": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'trending-up-icon' }) })),
    zap: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'zap-icon' }) })),
    flag: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'flag-icon' }) })),
    shield: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'shield-icon' }) })),
    activity: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'activity-icon' }) })),
    map: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'map-icon' }) })),
    "map-pin": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'map-pin-icon' }) })),
    "message-circle": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'message-icon' }) })),
    home: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'home-icon' }) })),
    "refresh-cw": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'refresh-cw-icon' }) })),
    wrench: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'wrench-icon' }) })),
    "help-circle": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'help-circle-icon' }) })),
    bug: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'bug-icon' }) })),
    "wifi-off": vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'wifi-off-icon' }) })),
    server: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'server-icon' }) })),
    save: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'save-icon' }) })),
    download: vi.fn(() => Promise.resolve({ default: () => React.createElement('svg', { 'data-testid': 'download-icon' }) })),
    upload: vi.fn(() => Promise.resolve({ default: () => null })),
    search: vi.fn(() => Promise.resolve({ default: () => null })),
    filter: vi.fn(() => Promise.resolve({ default: () => null })),
    image: vi.fn(() => Promise.resolve({ default: () => null })),
    camera: vi.fn(() => Promise.resolve({ default: () => null })),
    "arrow-left": vi.fn(() => Promise.resolve({ default: () => null })),
    "arrow-right": vi.fn(() => Promise.resolve({ default: () => null })),
    "arrow-up": vi.fn(() => Promise.resolve({ default: () => null })),
    "arrow-down": vi.fn(() => Promise.resolve({ default: () => null })),
    "chevron-down": vi.fn(() => Promise.resolve({ default: () => null })),
    "chevron-up": vi.fn(() => Promise.resolve({ default: () => null })),
    "chevron-left": vi.fn(() => Promise.resolve({ default: () => null })),
    "chevron-right": vi.fn(() => Promise.resolve({ default: () => null })),
    play: vi.fn(() => Promise.resolve({ default: () => null })),
    pause: vi.fn(() => Promise.resolve({ default: () => null })),
    book: vi.fn(() => Promise.resolve({ default: () => null })),
    file: vi.fn(() => Promise.resolve({ default: () => null })),
    "file-text": vi.fn(() => Promise.resolve({ default: () => null })),
    copy: vi.fn(() => Promise.resolve({ default: () => null })),
    folder: vi.fn(() => Promise.resolve({ default: () => null })),
    database: vi.fn(() => Promise.resolve({ default: () => null })),
    phone: vi.fn(() => Promise.resolve({ default: () => null })),
    mail: vi.fn(() => Promise.resolve({ default: () => null })),
    eye: vi.fn(() => Promise.resolve({ default: () => null })),
    "eye-off": vi.fn(() => Promise.resolve({ default: () => null })),
    lock: vi.fn(() => Promise.resolve({ default: () => null })),
    unlock: vi.fn(() => Promise.resolve({ default: () => null })),
    key: vi.fn(() => Promise.resolve({ default: () => null })),
    hash: vi.fn(() => Promise.resolve({ default: () => null })),
    "clipboard-list": vi.fn(() => Promise.resolve({ default: () => null })),
    "check-circle": vi.fn(() => Promise.resolve({ default: () => null })),
    grid: vi.fn(() => Promise.resolve({ default: () => null })),
    power: vi.fn(() => Promise.resolve({ default: () => null })),
    "mouse-pointer": vi.fn(() => Promise.resolve({ default: () => null })),
    hand: vi.fn(() => Promise.resolve({ default: () => null })),
    move: vi.fn(() => Promise.resolve({ default: () => null })),
    "pen-tool": vi.fn(() => Promise.resolve({ default: () => null })),
    link: vi.fn(() => Promise.resolve({ default: () => null })),
    sparkles: vi.fn(() => Promise.resolve({ default: () => null })),
    crown: vi.fn(() => Promise.resolve({ default: () => null })),
    "toggle-right": vi.fn(() => Promise.resolve({ default: () => null })),
    "toggle-left": vi.fn(() => Promise.resolve({ default: () => null })),
    settings: vi.fn(() => Promise.resolve({ default: () => null })),
    "gamepad-2": vi.fn(() => Promise.resolve({ default: () => null })),
    inbox: vi.fn(() => Promise.resolve({ default: () => null })),
    "flask-conical": vi.fn(() => Promise.resolve({ default: () => null })),
    sprout: vi.fn(() => Promise.resolve({ default: () => null })),
    lightbulb: vi.fn(() => Promise.resolve({ default: () => null })),
    rocket: vi.fn(() => Promise.resolve({ default: () => null })),
    "party-popper": vi.fn(() => Promise.resolve({ default: () => null })),
    type: vi.fn(() => Promise.resolve({ default: () => null })),
    list: vi.fn(() => Promise.resolve({ default: () => null })),
    circle: vi.fn(() => Promise.resolve({ default: () => null })),
    "graduation-cap": vi.fn(() => Promise.resolve({ default: () => null })),
    shirt: vi.fn(() => Promise.resolve({ default: () => null })),
  },
}));

// Mock ModularIcon to prevent state updates after unmount in tests
vi.mock("../components/ui/Icon/ModularIcon.tsx", () => ({
  ModularIcon: vi.fn(() => null),
  ModularIconName: {},
  ModularIconProps: {},
  ModularPlayIcon: vi.fn(() => null),
  ModularEditIcon: vi.fn(() => null),
  ModularDeleteIcon: vi.fn(() => null),
  ModularAddIcon: vi.fn(() => null),
  ModularCalendarIcon: vi.fn(() => null),
  ModularClockIcon: vi.fn(() => null),
  ModularTeamIcon: vi.fn(() => null),
  ModularSettingsIcon: vi.fn(() => null),
}));
