import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";
import auroraTheme from "./src/styles/tailwind/auroraTheme.js";
import boxcallTheme from "./src/styles/tailwind/boxcallTheme.js";
import layoutTokens from "./src/styles/tailwind/layoutTokens.js";

const colorSteps = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900];
const statusSteps = [50, 500, 600, 700];

const createScale = (tokenName, steps = colorSteps) =>
  steps.reduce((acc, step) => {
    acc[step] = `var(--color-${tokenName}-${step})`;
    return acc;
  }, {});

const semanticColor = (name) => `var(--semantic-${name})`;

const spacingTokens = {
  0: "var(--space-0)",
  0.5: "var(--spacing-fine-0-5)",
  1: "var(--space-1)",
  1.5: "var(--spacing-fine-1-5)",
  2: "var(--space-2)",
  2.5: "var(--spacing-fine-2-5)",
  3: "var(--space-3)",
  3.5: "var(--spacing-fine-3-5)",
  4: "var(--space-4)",
  5: "var(--space-5)",
  6: "var(--space-6)",
  8: "var(--space-8)",
  10: "var(--space-10)",
  12: "var(--space-12)",
  16: "var(--space-16)",
  px: "1px",
  18: "4.5rem",
  88: "22rem",
  128: "32rem",
  "spacing-xs": "var(--space-2)",
  "spacing-sm": "var(--space-3)",
  "spacing-md": "var(--space-4)",
  "spacing-lg": "var(--space-6)",
  "spacing-xl": "var(--space-8)",
  "spacing-2xl": "var(--space-12)",
  "spacing-3xl": "var(--space-16)",
  "button-padding": "var(--spacing-buttonPadding)",
  "button-padding-lg": "var(--spacing-buttonPaddingLarge)",
  "card-padding": "var(--spacing-cardPadding)",
  "card-padding-lg": "var(--spacing-cardPaddingLarge)",
  "input-padding": "var(--spacing-inputPadding)",
  "section-gap": "var(--spacing-sectionGap)",
  "item-gap": "var(--spacing-itemSpacing)",
  "list-gap": "var(--spacing-listGap)",
  "stack-tight": "var(--spacing-stackTight)",
  "stack-normal": "var(--spacing-stackNormal)",
  "stack-relaxed": "var(--spacing-stackRelaxed)",
  "stack-loose": "var(--spacing-stackLoose)",
};

const elevationTokens = {
  none: "var(--elevation-none)",
  sm: "var(--elevation-sm)",
  DEFAULT: "var(--elevation-md)",
  md: "var(--elevation-md)",
  lg: "var(--elevation-lg)",
  xl: "var(--elevation-xl)",
  "2xl": "var(--elevation-2xl)",
  focus: "var(--elevation-focus)",
  card: "var(--elevation-card-resting)",
  "card-hover": "var(--elevation-card-hover)",
  "card-active": "var(--elevation-card-active)",
  button: "var(--elevation-button-resting)",
  "button-hover": "var(--elevation-button-hover)",
  "button-active": "var(--elevation-button-active)",
  dropdown: "var(--elevation-dropdown)",
  modal: "var(--elevation-modal)",
};

const opacityTokens = {
  0: "var(--opacity-0)",
  5: "var(--opacity-5)",
  10: "var(--opacity-10)",
  15: "var(--opacity-15)",
  20: "var(--opacity-20)",
  30: "var(--opacity-30)",
  40: "var(--opacity-40)",
  50: "var(--opacity-50)",
  60: "var(--opacity-60)",
  70: "var(--opacity-70)",
  75: "var(--opacity-75)",
  80: "var(--opacity-80)",
  90: "var(--opacity-90)",
  95: "var(--opacity-95)",
  100: "var(--opacity-100)",
};

const diagramTokens = {
  annotation: "var(--color-diagram-annotationColor)",
  "annotation-highlight": "var(--color-diagram-annotationHighlight)",
  "annotation-connector": "var(--color-diagram-annotationConnector)",
  "annotation-selection": "var(--color-diagram-annotationSelection)",
  "field-background": "var(--color-diagram-fieldBackground)",
  "field-background-dark": "var(--color-diagram-fieldBackgroundDark)",
  "field-border": "var(--color-diagram-fieldBorder)",
  "field-zone": "var(--color-diagram-fieldZone)",
  grid: "var(--color-diagram-gridColor)",
  "grid-dark": "var(--color-diagram-gridColorDark)",
  guide: "var(--color-diagram-guideColor)",
  "minimap-background": "var(--color-diagram-minimapBackground)",
  "minimap-border": "var(--color-diagram-minimapBorder)",
  offense: "var(--color-diagram-offensivePlayer)",
  "offense-alt": "var(--color-diagram-offensivePlayerAlt)",
  defense: "var(--color-diagram-defensivePlayer)",
  "defense-alt": "var(--color-diagram-defensivePlayerAlt)",
  "special-teams": "var(--color-diagram-specialTeamsPlayer)",
  route: "var(--color-diagram-routeColor)",
  "route-alt": "var(--color-diagram-routeColorAlt)",
  "route-start": "var(--color-diagram-routeStart)",
  "route-end": "var(--color-diagram-routeEnd)",
};

const colors = {
  jade: createScale("jade"),
  navy: createScale("navy"),
  gray: createScale("gray"),
  blue: createScale("blue"),
  cyan: createScale("cyan"),
  amber: createScale("amber"),
  emerald: createScale("emerald"),
  purple: createScale("purple"),
  violet: createScale("violet"),
  red: createScale("red"),
  success: createScale("success", statusSteps),
  warning: createScale("warning", statusSteps),
  error: createScale("error", statusSteps),
  brand: {
    primary: semanticColor("primary"),
    hover: semanticColor("primary-hover"),
    active: semanticColor("primary-active"),
  },
  surface: {
    base: semanticColor("bg-primary"),
    secondary: semanticColor("bg-secondary"),
    muted: semanticColor("bg-muted"),
    subtle: semanticColor("surface-subtle-hover"),
    inverse: semanticColor("surface-inverse"),
    "inverse-alt": semanticColor("surface-inverse-alt"),
  },
  text: {
    primary: semanticColor("text-primary"),
    secondary: semanticColor("text-secondary"),
    muted: semanticColor("text-muted"),
    inverse: semanticColor("text-inverse"),
    brand: semanticColor("text-brand"),
  },
  border: {
    DEFAULT: semanticColor("border"),
    focus: semanticColor("border-focus"),
    error: semanticColor("border-error"),
    subtle: "var(--border-color-subtle)",
    medium: "var(--border-color-medium)",
    strong: "var(--border-color-strong)",
    brand: "var(--border-color-brand)",
    "brand-strong": "var(--border-color-brand-strong)",
    interactive: "var(--border-color-interactive)",
    "interactive-strong": "var(--border-color-interactive-strong)",
  },
  status: {
    success: semanticColor("success"),
    "success-bg": semanticColor("success-bg"),
    warning: semanticColor("warning"),
    "warning-bg": semanticColor("warning-bg"),
    error: semanticColor("error"),
    "error-bg": semanticColor("error-bg"),
    info: semanticColor("info"),
    "info-bg": semanticColor("info-bg"),
  },
  link: {
    DEFAULT: "var(--color-linkColor)",
    hover: "var(--color-linkHoverColor)",
    visited: "var(--color-linkVisitedColor)",
  },
  highlight: {
    DEFAULT: "var(--color-highlightColor)",
    bg: "var(--color-highlightBg)",
    selection: "var(--color-selectionColor)",
    "selection-bg": "var(--color-selectionBg)",
    "selection-border": "var(--color-selectionBorder)",
  },
  diagram: diagramTokens,
};

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors,
      spacing: spacingTokens,
      maxWidth: {
        // Layout container tokens
        "container-xs": "var(--layout-container-xs)",
        "container-sm": "var(--layout-container-sm)",
        "container-md": "var(--layout-container-md)",
        "container-lg": "var(--layout-container-lg)",
        "container-xl": "var(--layout-container-xl)",
        "container-2xl": "var(--layout-container-2xl)",
        "container-3xl": "var(--layout-container-3xl)",
        "container-4xl": "var(--layout-container-4xl)",
        "container-5xl": "var(--layout-container-5xl)",
        "container-6xl": "var(--layout-container-6xl)",
        "container-7xl": "var(--layout-container-7xl)",
        "container-full": "var(--layout-container-full)",
        // Semantic content widths
        "content-narrow": "var(--layout-content-narrow)",
        "content-medium": "var(--layout-content-medium)",
        "content-wide": "var(--layout-content-wide)",
        "content-full": "var(--layout-content-full)",
      },
      fontFamily: {
        display: ["Bebas Neue", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Consolas", "monospace"],
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "0.875rem", fontWeight: "400" }], // 10px - for ultra-compact UI (badges, labels)
        xs: ["0.75rem", { lineHeight: "1rem", fontWeight: "400" }],
        sm: ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        base: ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        lg: ["1.125rem", { lineHeight: "1.75rem", fontWeight: "500" }],
        xl: ["1.25rem", { lineHeight: "1.75rem", fontWeight: "600" }],
        "2xl": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem", fontWeight: "700" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem", fontWeight: "700" }],
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-button)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      borderWidth: {
        DEFAULT: "var(--border-width-thin)",
        0: "0",
        hairline: "var(--border-width-hairline)",
        thin: "var(--border-width-thin)",
        medium: "var(--border-width-medium)",
        thick: "var(--border-width-thick)",
        heavy: "var(--border-width-heavy)",
        2: "var(--border-width-medium)",
        3: "var(--border-width-thick)",
        4: "var(--border-width-heavy)",
      },
      boxShadow: elevationTokens,
      opacity: opacityTokens,
      zIndex: {
        auto: "auto",
        0: "0",
        10: "10",
        20: "20",
        30: "30",
        40: "40",
        50: "50",
        base: "0",
        dropdown: "40",
        sticky: "45",
        modal: "50",
        popover: "50",
        toast: "55",
        tooltip: "60",
      },
    },
  },
  plugins: [
    forms({ strategy: "class" }), // Only apply form styles when using form-* classes
    typography,
    auroraTheme,
    boxcallTheme,
    layoutTokens,
  ],
};
