import type { ComponentType } from "react";
import type { IconName } from "./Icon";

// Dynamic imports for perfect tree shaking (limited to our supported set)
type LucideComponent = ComponentType<{
  size?: number;
  color?: string;
  strokeWidth?: number;
  className?: string;
}>;
type Loader = () => Promise<{ default: LucideComponent } | LucideComponent>;

export const iconRegistry = new Map<IconName, LucideComponent>();

export const iconLoaders: Partial<Record<IconName, Loader>> = {
  activity: () => import("lucide-react/dist/esm/icons/activity.js"),
  alert: () => import("lucide-react/dist/esm/icons/alert-triangle.js"),
  "alert-circle": () => import("lucide-react/dist/esm/icons/alert-circle.js"),
  "alert-octagon": () => import("lucide-react/dist/esm/icons/alert-octagon.js"),
  "alert-triangle": () =>
    import("lucide-react/dist/esm/icons/alert-triangle.js"),
  "arrow-down": () => import("lucide-react/dist/esm/icons/arrow-down.js"),
  "arrow-left": () => import("lucide-react/dist/esm/icons/arrow-left.js"),
  "arrow-right": () => import("lucide-react/dist/esm/icons/arrow-right.js"),
  "arrow-up": () => import("lucide-react/dist/esm/icons/arrow-up.js"),
  award: () => import("lucide-react/dist/esm/icons/award.js"),
  "bar-chart": () => import("lucide-react/dist/esm/icons/bar-chart.js"),
  book: () => import("lucide-react/dist/esm/icons/book.js"),
  boxcall: () => import("lucide-react/dist/esm/icons/box.js"),
  calendar: () => import("lucide-react/dist/esm/icons/calendar.js"),
  camera: () => import("lucide-react/dist/esm/icons/camera.js"),
  check: () => import("lucide-react/dist/esm/icons/check.js"),
  "check-circle": () => import("lucide-react/dist/esm/icons/check-circle.js"),
  "chevron-down": () => import("lucide-react/dist/esm/icons/chevron-down.js"),
  "chevron-left": () => import("lucide-react/dist/esm/icons/chevron-left.js"),
  "chevron-right": () => import("lucide-react/dist/esm/icons/chevron-right.js"),
  "chevron-up": () => import("lucide-react/dist/esm/icons/chevron-up.js"),
  clock: () => import("lucide-react/dist/esm/icons/clock.js"),
  close: () => import("lucide-react/dist/esm/icons/x.js"),
  copy: () => import("lucide-react/dist/esm/icons/copy.js"),
  crown: () => import("lucide-react/dist/esm/icons/crown.js"),
  database: () => import("lucide-react/dist/esm/icons/database.js"),
  delete: () => import("lucide-react/dist/esm/icons/trash-2.js"),
  download: () => import("lucide-react/dist/esm/icons/download.js"),
  edit: () => import("lucide-react/dist/esm/icons/edit-3.js"),
  eye: () => import("lucide-react/dist/esm/icons/eye.js"),
  "eye-off": () => import("lucide-react/dist/esm/icons/eye-off.js"),
  file: () => import("lucide-react/dist/esm/icons/file.js"),
  filter: () => import("lucide-react/dist/esm/icons/filter.js"),
  flag: () => import("lucide-react/dist/esm/icons/flag.js"),
  folder: () => import("lucide-react/dist/esm/icons/folder.js"),
  forward: () => import("lucide-react/dist/esm/icons/arrow-right.js"),
  "gamepad-2": () => import("lucide-react/dist/esm/icons/gamepad-2.js"),
  grid: () => import("lucide-react/dist/esm/icons/grid.js"),
  hand: () => import("lucide-react/dist/esm/icons/hand.js"),
  "help-circle": () => import("lucide-react/dist/esm/icons/help-circle.js"),
  home: () => import("lucide-react/dist/esm/icons/home.js"),
  image: () => import("lucide-react/dist/esm/icons/image.js"),
  info: () => import("lucide-react/dist/esm/icons/info.js"),
  key: () => import("lucide-react/dist/esm/icons/key.js"),
  link: () => import("lucide-react/dist/esm/icons/link.js"),
  list: () => import("lucide-react/dist/esm/icons/list.js"),
  lock: () => import("lucide-react/dist/esm/icons/lock.js"),
  mail: () => import("lucide-react/dist/esm/icons/mail.js"),
  map: () => import("lucide-react/dist/esm/icons/map.js"),
  "map-pin": () => import("lucide-react/dist/esm/icons/map-pin.js"),
  medal: () => import("lucide-react/dist/esm/icons/medal.js"),
  menu: () => import("lucide-react/dist/esm/icons/menu.js"),
  message: () => import("lucide-react/dist/esm/icons/message-circle.js"),
  minus: () => import("lucide-react/dist/esm/icons/minus.js"),
  move: () => import("lucide-react/dist/esm/icons/move.js"),
  "party-popper": () => import("lucide-react/dist/esm/icons/party-popper.js"),
  pause: () => import("lucide-react/dist/esm/icons/pause.js"),
  "pen-tool": () => import("lucide-react/dist/esm/icons/pen-tool.js"),
  phone: () => import("lucide-react/dist/esm/icons/phone.js"),
  play: () => import("lucide-react/dist/esm/icons/play.js"),
  plus: () => import("lucide-react/dist/esm/icons/plus.js"),
  "plus-circle": () => import("lucide-react/dist/esm/icons/plus-circle.js"),
  pointer: () => import("lucide-react/dist/esm/icons/mouse-pointer.js"),
  power: () => import("lucide-react/dist/esm/icons/power.js"),
  refresh: () => import("lucide-react/dist/esm/icons/refresh-cw.js"),
  "refresh-cw": () => import("lucide-react/dist/esm/icons/refresh-cw.js"),
  rocket: () => import("lucide-react/dist/esm/icons/rocket.js"),
  save: () => import("lucide-react/dist/esm/icons/save.js"),
  search: () => import("lucide-react/dist/esm/icons/search.js"),
  settings: () => import("lucide-react/dist/esm/icons/settings.js"),
  shield: () => import("lucide-react/dist/esm/icons/shield.js"),
  sparkles: () => import("lucide-react/dist/esm/icons/sparkles.js"),
  sprout: () => import("lucide-react/dist/esm/icons/sprout.js"),
  star: () => import("lucide-react/dist/esm/icons/star.js"),
  tag: () => import("lucide-react/dist/esm/icons/tag.js"),
  target: () => import("lucide-react/dist/esm/icons/target.js"),
  team: () => import("lucide-react/dist/esm/icons/users.js"),
  trophy: () => import("lucide-react/dist/esm/icons/trophy.js"),
  type: () => import("lucide-react/dist/esm/icons/type.js"),
  undo: () => import("lucide-react/dist/esm/icons/undo-2.js"),
  unlock: () => import("lucide-react/dist/esm/icons/unlock.js"),
  upload: () => import("lucide-react/dist/esm/icons/upload.js"),
  user: () => import("lucide-react/dist/esm/icons/user.js"),
  "user-plus": () => import("lucide-react/dist/esm/icons/user-plus.js"),
  users: () => import("lucide-react/dist/esm/icons/users.js"),
  warning: () => import("lucide-react/dist/esm/icons/alert-triangle.js"),
  wifi: () => import("lucide-react/dist/esm/icons/wifi.js"),
  "wifi-off": () => import("lucide-react/dist/esm/icons/wifi-off.js"),
  wrench: () => import("lucide-react/dist/esm/icons/wrench.js"),
  zap: () => import("lucide-react/dist/esm/icons/zap.js"),
  maximize: () => import("lucide-react/dist/esm/icons/maximize.js"),
};
