/**
 * Enhanced Service Worker for BoxCall PWA
 *
 * Features:
 * - Cache-first for static assets (HTML, CSS, JS, images)
 * - Network-first for API calls with fallback
 * - Stale-while-revalidate for data freshness
 * - Offline page support
 * - Background sync for failed requests
 * - Push notifications (future)
 */

import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import {
  CacheFirst,
  NetworkFirst,
  StaleWhileRevalidate,
} from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";
import { CacheableResponsePlugin } from "workbox-cacheable-response";

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST);

// Cache names
const CACHE_VERSION = "v1";
const CACHE_NAMES = {
  static: `static-${CACHE_VERSION}`,
  api: `api-${CACHE_VERSION}`,
  images: `images-${CACHE_VERSION}`,
  fonts: `fonts-${CACHE_VERSION}`,
};

// =====================================================
// STRATEGY 1: Cache-First for Static Assets (OPTIMIZED)
// =====================================================

// Cache JavaScript and CSS files (versioned, immutable) - INCREASED CACHE SIZE
registerRoute(
  ({ request }) =>
    request.destination === "script" || request.destination === "style",
  new CacheFirst({
    cacheName: CACHE_NAMES.static,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100, // Increased from 60
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days (from 30)
      }),
    ],
  })
);

// Cache fonts (rarely change) - OPTIMIZED
registerRoute(
  ({ request }) => request.destination === "font",
  new CacheFirst({
    cacheName: CACHE_NAMES.fonts,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50, // Increased from 30
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// =====================================================
// STRATEGY 2: Stale-While-Revalidate for Images (OPTIMIZED)
// =====================================================

// Cache images with stale-while-revalidate - INCREASED CACHE SIZE
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate({
    cacheName: CACHE_NAMES.images,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 200, // Increased from 100
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days (from 7)
      }),
    ],
  })
);

// =====================================================
// STRATEGY 3: Network-First for API Calls (OPTIMIZED)
// =====================================================

// Supabase API calls - network-first with optimized timeout and cache
registerRoute(
  ({ url }) => url.hostname.includes("supabase.co"),
  new NetworkFirst({
    cacheName: CACHE_NAMES.api,
    networkTimeoutSeconds: 5, // Increased from 3s for better reliability
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100, // Increased from 50
        maxAgeSeconds: 15 * 60, // 15 minutes (from 5)
      }),
    ],
  })
);

// =====================================================
// STRATEGY 4: Cache-First for External Resources
// =====================================================

// Cache external resources (CDNs, etc.) with longer timeout
registerRoute(
  ({ url }) =>
    url.hostname !== location.hostname &&
    !url.hostname.includes("supabase.co"),
  new CacheFirst({
    cacheName: "external-resources",
    networkTimeoutSeconds: 10,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// =====================================================
// STRATEGY 4: Stale-While-Revalidate for Navigation
// =====================================================

// HTML documents (app shell)
registerRoute(
  ({ request }) => request.mode === "navigate",
  new NetworkFirst({
    cacheName: CACHE_NAMES.static,
    networkTimeoutSeconds: 3,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// =====================================================
// OFFLINE FALLBACK
// =====================================================

// Cache offline page during installation
self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAMES.static).then((cache) => {
      return cache.addAll(["/offline.html", "/favicon.ico"]).catch((err) => {
        console.error("Failed to cache offline resources:", err);
      });
    })
  );

  // Skip waiting to activate immediately
  self.skipWaiting();
});

// Activate immediately
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          // Delete old caches
          if (!Object.values(CACHE_NAMES).includes(cacheName)) {
            console.log("Deleting old cache:", cacheName);
            return caches.delete(cacheName);
          }
        })
      );
    })
  );

  // Take control of all clients immediately
  return self.clients.claim();
});

// Serve offline page when network fails
self.addEventListener("fetch", (event) => {
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request).catch(() => {
        return caches.match("/offline.html").then((response) => {
          return response || new Response("Offline");
        });
      })
    );
  }
});

// =====================================================
// BACKGROUND SYNC (for failed requests)
// =====================================================

// Register background sync for failed POST/PUT requests
self.addEventListener("sync", (event: any) => {
  if (event.tag === "sync-failed-requests") {
    event.waitUntil(
      // Retry failed requests from IndexedDB queue
      replayFailedRequests()
    );
  }
});

async function replayFailedRequests() {
  // Implementation would retrieve failed requests from IndexedDB
  // and retry them when network is available
  console.log("Replaying failed requests...");
}

// =====================================================
// PUSH NOTIFICATIONS (future feature)
// =====================================================

self.addEventListener("push", (event) => {
  const data = event.data?.json() ?? {};

  event.waitUntil(
    self.registration.showNotification(data.title || "BoxCall Notification", {
      body: data.body || "",
      icon: "/icon-192x192.png",
      badge: "/badge-72x72.png",
      data: data.data,
    })
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();

  event.waitUntil(self.clients.openWindow(event.notification.data?.url || "/"));
});

// =====================================================
// PERFORMANCE MONITORING
// =====================================================

// Log cache hit rates in development
if (import.meta.env.DEV) {
  let cacheHits = 0;
  let cacheMisses = 0;

  self.addEventListener("fetch", (event) => {
    event.respondWith(
      caches.match(event.request).then((response) => {
        if (response) {
          cacheHits++;
          console.log(
            `✅ Cache hit (${cacheHits}/${cacheHits + cacheMisses}):`,
            event.request.url
          );
        } else {
          cacheMisses++;
          console.log(
            `❌ Cache miss (${cacheHits}/${cacheHits + cacheMisses}):`,
            event.request.url
          );
        }
        return response || fetch(event.request);
      })
    );
  });
}

console.log(
  "✅ BoxCall Service Worker registered with enhanced caching strategies"
);
