import type { ThemeDefinition, ThemeRegistryExport } from "./types";
import { colorTokens } from "../design-system/tokens";

// Base (light) theme derived from existing semantic tokens in tokens.ts
export const lightTheme: ThemeDefinition = {
  id: "light",
  label: "Light",
  version: 1,
  mode: "light",
  semantic: {
    primary: "#00A86B",
    primaryHover: colorTokens.emerald[700],
    primaryActive: colorTokens.emerald[800],
    textPrimary: colorTokens.gray[900],
    textSecondary: colorTokens.gray[600],
    textMuted: colorTokens.gray[500],
    textInverse: "#ffffff",
    textBrand: colorTokens.emerald[700],
    bgPrimary: "#ffffff",
    bgSecondary: colorTokens.gray[50],
    bgMuted: colorTokens.gray[100],
    surfaceSubtleHover: colorTokens.gray[100],
    surfaceInverse: colorTokens.gray[900],
    surfaceInverseAlt: colorTokens.gray[700],
    border: colorTokens.gray[200],
    borderFocus: "#00A86B",
    borderError: colorTokens.red[500],
    focusRing: colorTokens.emerald[700],
    success: colorTokens.emerald[500],
    successBg: "#F0FDF4",
    warning: colorTokens.amber[500],
    warningBg: colorTokens.amber[50],
    error: colorTokens.red[500],
    errorBg: colorTokens.red[50],
  },
  description: "Default light theme.",
};

export const darkTheme: ThemeDefinition = {
  id: "dark",
  label: "Dark",
  version: 1,
  mode: "dark",
  semantic: {
    primary: "#00A86B",
    primaryHover: colorTokens.emerald[400], // slightly lighter hover in dark
    primaryActive: colorTokens.emerald[700],
    textPrimary: colorTokens.gray[50],
    textSecondary: colorTokens.gray[300],
    textMuted: colorTokens.gray[400],
    textInverse: colorTokens.gray[900],
    textBrand: colorTokens.emerald[400],
    bgPrimary: colorTokens.gray[900],
    bgSecondary: colorTokens.gray[800],
    bgMuted: colorTokens.gray[700],
    surfaceSubtleHover: "rgba(55,65,81,0.85)",
    surfaceInverse: colorTokens.gray[700],
    surfaceInverseAlt: colorTokens.gray[600],
    border: colorTokens.gray[700],
    borderFocus: "#00A86B",
    borderError: colorTokens.red[400],
    focusRing: "#00A86B",
    success: colorTokens.emerald[500],
    successBg: colorTokens.emerald[900],
    warning: colorTokens.amber[500],
    warningBg: "#78350F",
    error: colorTokens.red[500],
    errorBg: "#7F1D1D",
  },
  description: "Dark theme tuned for contrast.",
};

export const highContrastTheme: ThemeDefinition = {
  id: "high-contrast",
  label: "High Contrast",
  version: 1,
  mode: "high-contrast",
  semantic: {
    primary: colorTokens.emerald[800],
    primaryHover: "#00A86B",
    primaryActive: colorTokens.emerald[700],
    textPrimary: "#000000",
    textSecondary: colorTokens.gray[900],
    textMuted: colorTokens.gray[800],
    textInverse: "#ffffff",
    textBrand: colorTokens.emerald[800],
    bgPrimary: "#ffffff",
    bgSecondary: colorTokens.gray[100],
    bgMuted: colorTokens.gray[200],
    surfaceSubtleHover: colorTokens.gray[300],
    surfaceInverse: "#000000",
    surfaceInverseAlt: colorTokens.gray[900],
    border: colorTokens.gray[900],
    borderFocus: colorTokens.emerald[800],
    borderError: colorTokens.red[700],
    focusRing: colorTokens.emerald[800],
    success: "#166534",
    successBg: "#BBF7D0",
    warning: colorTokens.amber[700],
    warningBg: colorTokens.amber[200],
    error: colorTokens.red[700],
    errorBg: colorTokens.red[200],
  },
  description: "High contrast variant for accessibility / visual clarity.",
};

export const themeRegistry: ThemeRegistryExport = {
  themes: [
    lightTheme,
    darkTheme,
    highContrastTheme,
    {
      id: "cupertino-light",
      label: "Cupertino Light",
      version: 1,
      mode: "light",
      semantic: {
        primary: "#00A86B",
        primaryHover: "#069669",
        primaryActive: colorTokens.emerald[700],
        textPrimary: colorTokens.gray[900],
        textSecondary: "#3F3F46",
        textMuted: colorTokens.gray[500],
        textInverse: "#ffffff",
        textBrand: colorTokens.emerald[700],
        bgPrimary: "#F7F7F7",
        bgSecondary: "#ffffff",
        bgMuted: "#F2F2F7",
        surfaceSubtleHover: "#F2F2F7",
        surfaceInverse: colorTokens.gray[900],
        surfaceInverseAlt: colorTokens.gray[700],
        border: "rgba(60,60,67,0.18)",
        borderFocus: "#00A86B",
        borderError: colorTokens.red[500],
        focusRing: "#0A84FF",
        success: "#34C759",
        successBg: "#EAFBEF",
        warning: "#FF9F0A",
        warningBg: "#FFF6E5",
        error: "#FF3B30",
        errorBg: "#FFE8E6",
      },
      component: {
        panel: {
          bg: "rgba(255,255,255,0.72)",
          border: "rgba(60,60,67,0.18)",
          radius: "12px",
          shadow: "0 0.5px 0 rgba(0,0,0,0.2), 0 10px 20px rgba(0,0,0,0.06)",
          blur: "20px",
        },
        button: {
          borderRadius: "10px",
          shadow: "0 1px 2px rgba(0,0,0,0.06), 0 3px 8px rgba(0,0,0,0.06)",
        },
      },
      description:
        "Soft, translucent panels with subtle borders and generous radius.",
    },
    {
      id: "cupertino-dark",
      label: "Cupertino Dark",
      version: 1,
      mode: "dark",
      semantic: {
        primary: "#00D186",
        primaryHover: colorTokens.emerald[400],
        primaryActive: colorTokens.emerald[500],
        textPrimary: "#F5F5F7",
        textSecondary: "#D1D1D6",
        textMuted: "#A1A1AA",
        textInverse: colorTokens.gray[900],
        textBrand: colorTokens.emerald[400],
        bgPrimary: "#0B0B0C",
        bgSecondary: "#1C1C1E",
        bgMuted: "#2C2C2E",
        surfaceSubtleHover: "rgba(44,44,46,0.8)",
        surfaceInverse: "#2C2C2E",
        surfaceInverseAlt: "#3A3A3C",
        border: "rgba(84,84,88,0.36)",
        borderFocus: "#00D186",
        borderError: "#FF453A",
        focusRing: "#0A84FF",
        success: "#32D74B",
        successBg: "#06310E",
        warning: "#FFD60A",
        warningBg: "#3A2C00",
        error: "#FF453A",
        errorBg: "#3B0B0B",
      },
      component: {
        panel: {
          bg: "rgba(28,28,30,0.72)",
          border: "rgba(84,84,88,0.36)",
          radius: "12px",
          shadow: "0 0.5px 0 rgba(0,0,0,0.4), 0 10px 20px rgba(0,0,0,0.3)",
          blur: "20px",
        },
        button: {
          borderRadius: "10px",
          shadow: "0 1px 2px rgba(0,0,0,0.3), 0 3px 8px rgba(0,0,0,0.3)",
        },
      },
      description:
        "Translucent dark panels and refined contrast in the Cupertino spirit.",
    },
  ],
  baseId: "light",
};

export function getTheme(id: string) {
  return themeRegistry.themes.find((t) => t.id === id);
}
