/**
 * Streamlined Play Builder - Single Screen Design
 * Clean interface with toggleable advanced sections
 */

import React, { useState } from "react";
import {
  X,
  Save,
  ChevronDown,
  ChevronRight,
  Plus,
  Target,
  Settings,
  Eye,
  Tag,
  Clock,
} from "lucide-react";
import type { Play, PlayType, CustomFieldValues } from "../../../types/play";
import { CustomFieldsGrouped } from "../CustomFields";
import { AddNewDropdown } from "./AddNewDropdown";
import { AutocompleteDropdown } from "./AutocompleteDropdown";

interface StreamlinedPlayBuilderProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (play: Partial<Play>) => void;
  initialPlay?: Partial<Play>;
  teamId?: string; // Required for custom fields
}

interface ToggleSection {
  id: string;
  title: string;
  icon: React.ReactNode;
  isOpen: boolean;
}

export const StreamlinedPlayBuilder: React.FC<StreamlinedPlayBuilderProps> = ({
  isOpen,
  onClose,
  onSave,
  initialPlay = {},
  teamId = "demo-team-1", // Default for development
}) => {
  // Form state with proper database defaults
  const [playData, setPlayData] = useState<Partial<Play>>({
    // Essential fields
    play_name: initialPlay.play_name || "",
    p_type: initialPlay.p_type || "",
    formation: initialPlay.formation || "",
    one_word_play: initialPlay.one_word_play || "",
    notes: initialPlay.notes || "",

    // Preference fields
    pref_down: initialPlay.pref_down || "",
    pref_dis: initialPlay.pref_dis || "",
    pref_hash: initialPlay.pref_hash || "",
    pref_cov: initialPlay.pref_cov || "",
    pref_front: initialPlay.pref_front || "",

    // Performance fields
    success_rate: initialPlay.success_rate || 0,
    confidence_base: initialPlay.confidence_base || 70,
    times_called: initialPlay.times_called || 0,
    times_successful: initialPlay.times_successful || 0,
    complexity_score: initialPlay.complexity_score || 1,

    // Formation details
    f_dir: initialPlay.f_dir || "",
    ftag1: initialPlay.ftag1 || "",
    ftag2: initialPlay.ftag2 || "",
    back_align: initialPlay.back_align || "",
    shift: initialPlay.shift || "",
    motion: initialPlay.motion || "",
    f_type: initialPlay.f_type || "",
    personnel: initialPlay.personnel || "",
    protection: initialPlay.protection || "",

    // Play details
    p_tag1: initialPlay.p_tag1 || "",
    p_tag2: initialPlay.p_tag2 || "",
    p_dir: initialPlay.p_dir || "",
    key_player1: initialPlay.key_player1 || "",
    key_player2: initialPlay.key_player2 || "",
    check_into: initialPlay.check_into || "",
    r_str: initialPlay.r_str || "",
    p_str: initialPlay.p_str || "",

    // Media and additional
    diagram_url: initialPlay.diagram_url || "",
    video_url: initialPlay.video_url || "",
    tags: initialPlay.tags || [],
    is_archived: initialPlay.is_archived || false,

    // Will be set by system
    // id: generated by database
    // playbook_id: from context
    // created_by: from auth user
    // created_at: set by database
    // updated_at: set by database
    // last_used_at: set when play is used
    // search_vector: generated by database

    ...initialPlay,
  });

  // Toggleable sections state
  const [sections, setSections] = useState<ToggleSection[]>([
    {
      id: "formation-details",
      title: "Formation Details & Mechanics",
      icon: <Target className="h-4 w-4" />,
      isOpen: false,
    },
    {
      id: "advanced-tags",
      title: "Advanced Tags & Categories",
      icon: <Tag className="h-4 w-4" />,
      isOpen: false,
    },
    {
      id: "preferred-situations",
      title: "Preferred Situations & Field Position",
      icon: <Target className="h-4 w-4" />,
      isOpen: false,
    },
    {
      id: "performance-data",
      title: "Performance Data & Analytics",
      icon: <Settings className="h-4 w-4" />,
      isOpen: false,
    },
    {
      id: "custom-fields",
      title: "Team Custom Fields",
      icon: <Settings className="h-4 w-4" />,
      isOpen: false,
    },
  ]);

  const toggleSection = (sectionId: string) => {
    setSections((prev) =>
      prev.map((section) =>
        section.id === sectionId
          ? { ...section, isOpen: !section.isOpen }
          : section
      )
    );
  };

  const updateField = (
    field: keyof Play,
    value: string | number | string[] | boolean | PlayType | CustomFieldValues
  ) => {
    setPlayData((prev) => ({ ...prev, [field]: value }));
  };

  const addTag = (tag: string) => {
    if (!tag.trim()) return;
    const currentTags = playData.tags || [];
    if (!currentTags.includes(tag)) {
      updateField("tags", [...currentTags, tag]);
    }
  };

  const removeTag = (tagToRemove: string) => {
    const currentTags = playData.tags || [];
    updateField(
      "tags",
      currentTags.filter((tag) => tag !== tagToRemove)
    );
  };

  const handleSave = () => {
    onSave(playData);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      <div className="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        {/* Backdrop */}
        <div
          className="fixed inset-0 bg-slate-900 bg-opacity-50 transition-opacity"
          onClick={onClose}
        />

        {/* Modal */}
        <div className="inline-block align-bottom bg-white rounded-lg shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-4xl sm:w-full max-h-[90vh] overflow-hidden">
          {/* Header */}
          <div className="bg-white px-6 py-4 border-b border-slate-200 flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <div className="bg-emerald-100 p-2 rounded-lg">
                <Plus className="h-5 w-5 text-emerald-600" />
              </div>
              <div>
                <h2 className="text-xl font-semibold text-slate-900">
                  {initialPlay?.id ? "Edit Play" : "Create New Play"}
                </h2>
                <p className="text-sm text-slate-500">
                  Build your play with essential details, add advanced options
                  as needed
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-slate-600 p-2 hover:bg-slate-100 rounded-lg transition-colors"
            >
              <X className="h-6 w-6" />
            </button>
          </div>

          {/* Content */}
          <div className="bg-white px-6 py-6 overflow-y-auto max-h-[calc(90vh-140px)]">
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              {/* Main Form - 2/3 width */}
              <div className="lg:col-span-2 space-y-6">
                {/* Essential Play Info - Always Visible */}
                <div className="bg-slate-50 rounded-lg p-6">
                  <h3 className="text-lg font-medium text-slate-900 mb-4 flex items-center">
                    <Eye className="h-5 w-5 mr-2 text-emerald-600" />
                    Essential Play Details
                  </h3>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {/* Play Name */}
                    <div className="md:col-span-2">
                      <label className="block text-sm font-medium text-slate-700 mb-2">
                        Play Name *
                      </label>
                      <input
                        type="text"
                        value={playData.play_name}
                        onChange={(e) =>
                          updateField("play_name", e.target.value)
                        }
                        placeholder="e.g., Smash Concept, Traffic, Corndog"
                        className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                      />
                    </div>

                    {/* Play Type */}
                    {/* Play Type */}
                    <AutocompleteDropdown
                      value={playData.p_type || ""}
                      onChange={(value) => updateField("p_type", value)}
                      options={[
                        "Pass",
                        "Run",
                        "RPO",
                        "Play Action",
                        "Screen",
                        "Special",
                      ]}
                      placeholder="Select or type play type..."
                      label="Play Type"
                      required={true}
                      onAddNew={(newValue) => {
                        // Could store new play types in team settings
                        console.log("New play type added:", newValue);
                      }}
                    />

                    {/* Formation */}
                    <AutocompleteDropdown
                      value={playData.formation || ""}
                      onChange={(value) => updateField("formation", value)}
                      options={[
                        "Shotgun",
                        "Pistol",
                        "I-Form",
                        "Singleback",
                        "Twins",
                        "Trips",
                        "Empty",
                        "Wildcat",
                      ]}
                      placeholder="Select or type formation..."
                      label="Formation"
                      required={false}
                      onAddNew={(newValue) => {
                        // Could store new formations in team settings
                        console.log("New formation added:", newValue);
                      }}
                    />

                    {/* Audible */}
                    <div>
                      <label className="block text-sm font-medium text-slate-700 mb-2">
                        Audible/Call Word
                      </label>
                      <input
                        type="text"
                        value={playData.one_word_play || ""}
                        onChange={(e) =>
                          updateField("one_word_play", e.target.value)
                        }
                        placeholder='e.g., "Corndog", "Alpha"'
                        className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                      />
                    </div>

                    {/* Notes */}
                    <div className="md:col-span-2">
                      <label className="block text-sm font-medium text-slate-700 mb-2">
                        Play Description & Notes
                      </label>
                      <textarea
                        value={playData.notes}
                        onChange={(e) => updateField("notes", e.target.value)}
                        rows={3}
                        placeholder="Describe the play, key coaching points, assignments..."
                        className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                      />
                    </div>
                  </div>
                </div>

                {/* Advanced Sections - Toggleable */}
                {sections.map((section) => (
                  <div
                    key={section.id}
                    className="border border-slate-200 rounded-lg"
                  >
                    <button
                      onClick={() => toggleSection(section.id)}
                      className="w-full flex items-center justify-between p-4 hover:bg-slate-50 transition-colors"
                    >
                      <div className="flex items-center space-x-3">
                        {section.icon}
                        <span className="font-medium text-slate-900">
                          {section.title}
                        </span>
                      </div>
                      {section.isOpen ? (
                        <ChevronDown className="h-5 w-5 text-slate-400" />
                      ) : (
                        <ChevronRight className="h-5 w-5 text-slate-400" />
                      )}
                    </button>

                    {/* Formation Details Section */}
                    {section.id === "formation-details" && section.isOpen && (
                      <div className="p-4 border-t border-slate-200 bg-slate-50">
                        <div className="grid grid-cols-2 gap-4 space-y-4">
                          <div className="col-span-2">
                            <h4 className="text-sm font-semibold text-slate-800 mb-3">
                              Formation Setup
                            </h4>
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Formation Direction
                            </label>
                            <select
                              value={playData.f_dir || ""}
                              onChange={(e) =>
                                updateField("f_dir", e.target.value)
                              }
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            >
                              <option value="">No preference</option>
                              <option value="left">Left</option>
                              <option value="right">Right</option>
                              <option value="balanced">Balanced</option>
                            </select>
                          </div>

                          {/* Personnel Package */}
                          <AutocompleteDropdown
                            value={playData.personnel || ""}
                            onChange={(value) =>
                              updateField("personnel", value)
                            }
                            options={[
                              "11 Personnel (3 WR, 1 TE, 1 RB)",
                              "12 Personnel (2 WR, 2 TE, 1 RB)",
                              "10 Personnel (4 WR, 0 TE, 1 RB)",
                              "21 Personnel (2 WR, 1 TE, 2 RB)",
                              "22 Personnel (1 WR, 1 TE, 3 RB)",
                            ]}
                            placeholder="Type or select personnel..."
                            label="Personnel Package"
                            required={false}
                            onAddNew={(newValue) => {
                              console.log(
                                "New personnel package added:",
                                newValue
                              );
                            }}
                          />

                          {/* RB Alignment */}
                          <AddNewDropdown
                            value={playData.back_align || ""}
                            onChange={(value) =>
                              updateField("back_align", value)
                            }
                            options={["I-Back", "Offset", "Split", "Wing"]}
                            placeholder="Standard"
                            label="RB Alignment"
                            required={false}
                          />

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Pre-Snap Motion
                            </label>
                            <input
                              type="text"
                              value={playData.motion || ""}
                              onChange={(e) =>
                                updateField("motion", e.target.value)
                              }
                              placeholder="e.g., Orbit, Jet, Wing motion"
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            />
                          </div>

                          {/* Protection Scheme */}
                          <AddNewDropdown
                            value={playData.protection || ""}
                            onChange={(value) =>
                              updateField("protection", value)
                            }
                            options={[
                              "6-Man Protection",
                              "7-Man Protection",
                              "Slide Protection",
                              "Big on Big",
                              "RPO Protection",
                            ]}
                            placeholder="Standard"
                            label="Protection Scheme"
                            required={false}
                          />

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Formation Shift
                            </label>
                            <input
                              type="text"
                              value={playData.shift || ""}
                              onChange={(e) =>
                                updateField("shift", e.target.value)
                              }
                              placeholder="e.g., Trips right shift, Stack"
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            />
                          </div>

                          <div className="col-span-2 pt-3 border-t border-slate-300">
                            <h5 className="text-sm font-semibold text-slate-800 mb-3">
                              Key Players & Execution
                            </h5>
                            <div className="grid grid-cols-2 gap-4">
                              <div>
                                <label className="block text-sm font-medium text-slate-700 mb-2">
                                  Primary Key Player
                                </label>
                                <select
                                  value={playData.key_player1 || ""}
                                  onChange={(e) =>
                                    updateField("key_player1", e.target.value)
                                  }
                                  className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                                >
                                  <option value="">None</option>
                                  <option value="QB">Quarterback</option>
                                  <option value="RB">Running Back</option>
                                  <option value="WR1">WR1</option>
                                  <option value="WR2">WR2</option>
                                  <option value="TE">Tight End</option>
                                </select>
                              </div>

                              <div>
                                <label className="block text-sm font-medium text-slate-700 mb-2">
                                  Secondary Key Player
                                </label>
                                <select
                                  value={playData.key_player2 || ""}
                                  onChange={(e) =>
                                    updateField("key_player2", e.target.value)
                                  }
                                  className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                                >
                                  <option value="">None</option>
                                  <option value="QB">Quarterback</option>
                                  <option value="RB">Running Back</option>
                                  <option value="WR1">WR1</option>
                                  <option value="WR2">WR2</option>
                                  <option value="WR3">WR3</option>
                                  <option value="TE">Tight End</option>
                                </select>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* Advanced Tags Section */}
                    {section.id === "advanced-tags" && section.isOpen && (
                      <div className="p-4 border-t border-slate-200 bg-slate-50">
                        <div className="space-y-4">
                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Tags (for easy searching)
                            </label>
                            <div className="flex flex-wrap gap-2 mb-3">
                              {(playData.tags || []).map((tag) => (
                                <span
                                  key={tag}
                                  className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-emerald-100 text-emerald-800"
                                >
                                  {tag}
                                  <button
                                    onClick={() => removeTag(tag)}
                                    className="ml-1.5 h-3 w-3 text-emerald-600 hover:text-emerald-800"
                                  >
                                    <X className="h-3 w-3" />
                                  </button>
                                </span>
                              ))}
                            </div>
                            <div className="flex space-x-2">
                              <input
                                type="text"
                                placeholder="Add tag (press Enter)"
                                className="flex-1 px-3 py-2 text-sm border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                                onKeyPress={(e) => {
                                  if (e.key === "Enter") {
                                    addTag(e.currentTarget.value);
                                    e.currentTarget.value = "";
                                  }
                                }}
                              />
                            </div>
                            <div className="mt-2 flex flex-wrap gap-1">
                              {[
                                "red-zone",
                                "goal-line",
                                "two-minute",
                                "third-down",
                                "short-yardage",
                                "long-yardage",
                              ].map((quickTag) => (
                                <button
                                  key={quickTag}
                                  onClick={() => addTag(quickTag)}
                                  className="text-xs px-2 py-1 bg-white border border-slate-300 rounded hover:bg-slate-50 text-slate-600"
                                >
                                  + {quickTag}
                                </button>
                              ))}
                            </div>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* Preferred Situations Section */}
                    {section.id === "preferred-situations" &&
                      section.isOpen && (
                        <div className="p-4 border-t border-slate-200 bg-slate-50">
                          <div className="grid grid-cols-2 gap-4 space-y-4">
                            <div className="col-span-2">
                              <h4 className="text-sm font-semibold text-slate-800 mb-3">
                                Game Situation Preferences
                              </h4>
                            </div>

                            <div>
                              <label className="block text-sm font-medium text-slate-700 mb-2">
                                Best Down
                              </label>
                              <select
                                value={playData.pref_down || ""}
                                onChange={(e) =>
                                  updateField("pref_down", e.target.value)
                                }
                                className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                              >
                                <option value="">Any down</option>
                                <option value="1">1st Down</option>
                                <option value="2">2nd Down</option>
                                <option value="3">3rd Down</option>
                                <option value="4">4th Down</option>
                              </select>
                            </div>

                            {/* Best Distance */}
                            <AddNewDropdown
                              value={playData.pref_dis || ""}
                              onChange={(value) =>
                                updateField("pref_dis", value)
                              }
                              options={[
                                "1-2 yards",
                                "3-5 yards",
                                "6-10 yards",
                                "11+ yards",
                              ]}
                              placeholder="Any distance"
                              label="Best Distance"
                              required={false}
                            />

                            {/* Hash Marks */}
                            <AddNewDropdown
                              value={playData.pref_hash || ""}
                              onChange={(value) =>
                                updateField("pref_hash", value)
                              }
                              options={["Left Hash", "Middle", "Right Hash"]}
                              placeholder="Any hash"
                              label="Hash Marks"
                              required={false}
                            />

                            <div>
                              <label className="block text-sm font-medium text-slate-700 mb-2">
                                Best vs Coverage
                              </label>
                              <select
                                value={playData.pref_cov || ""}
                                onChange={(e) =>
                                  updateField("pref_cov", e.target.value)
                                }
                                className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                              >
                                <option value="">Any coverage</option>
                                <option value="Cover-1">Cover 1</option>
                                <option value="Cover-2">Cover 2</option>
                                <option value="Cover-3">Cover 3</option>
                                <option value="Cover-4">Cover 4</option>
                                <option value="Man">Man Coverage</option>
                                <option value="Zone">Zone Coverage</option>
                                <option value="Press">Press Coverage</option>
                                <option value="Off">Off Coverage</option>
                              </select>
                            </div>

                            <div>
                              <label className="block text-sm font-medium text-slate-700 mb-2">
                                Best vs Front
                              </label>
                              <select
                                value={playData.pref_front || ""}
                                onChange={(e) =>
                                  updateField("pref_front", e.target.value)
                                }
                                className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                              >
                                <option value="">Any front</option>
                                <option value="4-3">4-3 Front</option>
                                <option value="3-4">3-4 Front</option>
                                <option value="5-2">5-2 Front</option>
                                <option value="6-1">6-1 Front</option>
                                <option value="Nickel">Nickel</option>
                                <option value="Dime">Dime</option>
                                <option value="Goal-Line">Goal Line</option>
                              </select>
                            </div>

                            <div>
                              <label className="block text-sm font-medium text-slate-700 mb-2">
                                Check/Audible Options
                              </label>
                              <input
                                type="text"
                                value={playData.check_into || ""}
                                onChange={(e) =>
                                  updateField("check_into", e.target.value)
                                }
                                placeholder="e.g., Quick slant, Draw, Screen"
                                className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                              />
                            </div>
                          </div>
                        </div>
                      )}

                    {/* Performance Data Section */}
                    {section.id === "performance-data" && section.isOpen && (
                      <div className="p-4 border-t border-slate-200 bg-slate-50">
                        <div className="grid grid-cols-2 gap-4 space-y-4">
                          <div className="col-span-2">
                            <h4 className="text-sm font-semibold text-slate-800 mb-3">
                              Performance Metrics & Analytics
                            </h4>
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Success Rate %
                            </label>
                            <input
                              type="number"
                              min="0"
                              max="100"
                              value={playData.success_rate || 0}
                              onChange={(e) =>
                                updateField(
                                  "success_rate",
                                  parseInt(e.target.value) || 0
                                )
                              }
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            />
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Base Confidence (1-100)
                            </label>
                            <input
                              type="number"
                              min="1"
                              max="100"
                              value={playData.confidence_base || 70}
                              onChange={(e) =>
                                updateField(
                                  "confidence_base",
                                  parseInt(e.target.value) || 70
                                )
                              }
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            />
                            <p className="text-xs text-slate-500 mt-1">
                              Coach confidence in play execution
                            </p>
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Times Called
                            </label>
                            <input
                              type="number"
                              min="0"
                              value={playData.times_called || 0}
                              onChange={(e) =>
                                updateField(
                                  "times_called",
                                  parseInt(e.target.value) || 0
                                )
                              }
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                              readOnly
                            />
                            <p className="text-xs text-slate-500 mt-1">
                              Auto-tracked during games
                            </p>
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Times Successful
                            </label>
                            <input
                              type="number"
                              min="0"
                              value={playData.times_successful || 0}
                              onChange={(e) =>
                                updateField(
                                  "times_successful",
                                  parseInt(e.target.value) || 0
                                )
                              }
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                              readOnly
                            />
                            <p className="text-xs text-slate-500 mt-1">
                              Auto-tracked during games
                            </p>
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Complexity Score (1-5)
                            </label>
                            <select
                              value={playData.complexity_score || 1}
                              onChange={(e) =>
                                updateField(
                                  "complexity_score",
                                  parseInt(e.target.value) || 1
                                )
                              }
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            >
                              <option value={1}>1 - Very Simple</option>
                              <option value={2}>2 - Simple</option>
                              <option value={3}>3 - Moderate</option>
                              <option value={4}>4 - Complex</option>
                              <option value={5}>5 - Very Complex</option>
                            </select>
                            <p className="text-xs text-slate-500 mt-1">
                              How difficult is this play to execute?
                            </p>
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Play Diagram URL
                            </label>
                            <input
                              type="url"
                              value={playData.diagram_url || ""}
                              onChange={(e) =>
                                updateField("diagram_url", e.target.value)
                              }
                              placeholder="https://example.com/play-diagram.png"
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            />
                          </div>

                          <div>
                            <label className="block text-sm font-medium text-slate-700 mb-2">
                              Instructional Video URL
                            </label>
                            <input
                              type="url"
                              value={playData.video_url || ""}
                              onChange={(e) =>
                                updateField("video_url", e.target.value)
                              }
                              placeholder="https://example.com/play-video.mp4"
                              className="w-full px-3 py-2 border border-slate-300 rounded-md focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                            />
                          </div>

                          <div className="col-span-2">
                            <label className="flex items-center space-x-2">
                              <input
                                type="checkbox"
                                checked={playData.is_archived || false}
                                onChange={(e) =>
                                  updateField("is_archived", e.target.checked)
                                }
                                className="h-4 w-4 text-emerald-600 focus:ring-emerald-500 border-slate-300 rounded"
                              />
                              <span className="text-sm font-medium text-slate-700">
                                Archive this play
                              </span>
                            </label>
                            <p className="text-xs text-slate-500 mt-1">
                              Archived plays won't appear in regular playbook
                              views
                            </p>
                          </div>
                        </div>
                      </div>
                    )}

                    {/* Custom Fields Section */}
                    {section.id === "custom-fields" && section.isOpen && (
                      <div className="p-4 border-t border-slate-200 bg-slate-50">
                        <div className="space-y-4">
                          <div>
                            <h4 className="text-sm font-semibold text-slate-800 mb-3">
                              Team Custom Fields
                            </h4>
                            <p className="text-xs text-slate-500 mb-4">
                              Define team-specific attributes for this play
                            </p>
                          </div>
                          <CustomFieldsGrouped
                            teamId={teamId}
                            customFields={playData.custom_fields || {}}
                            onCustomFieldsChange={(values: CustomFieldValues) =>
                              updateField("custom_fields", values)
                            }
                          />
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>

              {/* Preview Panel - 1/3 width */}
              <div className="lg:col-span-1">
                <div className="sticky top-0">
                  <div className="bg-emerald-50 rounded-lg p-6 border border-emerald-200">
                    <h3 className="text-lg font-medium text-emerald-900 mb-4 flex items-center">
                      <Eye className="h-5 w-5 mr-2" />
                      Live Preview
                    </h3>

                    {/* Play Card Preview */}
                    <div className="bg-white rounded-lg p-4 border border-emerald-200 space-y-3">
                      <div className="flex items-start justify-between">
                        <h4 className="font-semibold text-slate-900 text-lg">
                          {playData.play_name || "Untitled Play"}
                        </h4>
                        {playData.one_word_play && (
                          <span className="text-xs bg-slate-100 px-2 py-1 rounded">
                            "{playData.one_word_play}"
                          </span>
                        )}
                      </div>

                      <div className="flex items-center space-x-2">
                        {playData.p_type && (
                          <span className="text-xs bg-emerald-100 text-emerald-800 px-2 py-1 rounded-full">
                            {playData.p_type}
                          </span>
                        )}
                        {playData.formation && (
                          <span className="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded-full">
                            {playData.formation}
                          </span>
                        )}
                      </div>

                      {playData.notes && (
                        <p className="text-sm text-slate-600 italic">
                          {playData.notes.substring(0, 120)}
                          {playData.notes.length > 120 ? "..." : ""}
                        </p>
                      )}

                      {playData.tags && playData.tags.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {playData.tags.slice(0, 4).map((tag) => (
                            <span
                              key={tag}
                              className="text-xs bg-slate-100 text-slate-700 px-2 py-0.5 rounded"
                            >
                              #{tag}
                            </span>
                          ))}
                          {playData.tags.length > 4 && (
                            <span className="text-xs text-slate-500">
                              +{playData.tags.length - 4} more
                            </span>
                          )}
                        </div>
                      )}

                      {/* Preferred Situations */}
                      {(playData.pref_down ||
                        playData.pref_dis ||
                        playData.pref_hash) && (
                        <div className="pt-2 border-t border-slate-200">
                          <p className="text-xs font-medium text-slate-500 mb-1">
                            Best Used:
                          </p>
                          <div className="space-y-1 text-xs text-slate-600">
                            {playData.pref_down && (
                              <div>• {playData.pref_down} Down</div>
                            )}
                            {playData.pref_dis && (
                              <div>• {playData.pref_dis} yards to go</div>
                            )}
                            {playData.pref_hash && (
                              <div>• {playData.pref_hash} hash</div>
                            )}
                          </div>
                        </div>
                      )}

                      {playData.success_rate && playData.success_rate > 0 && (
                        <div className="flex items-center justify-between pt-2 border-t border-slate-200">
                          <span className="text-xs font-medium text-slate-500">
                            Success Rate
                          </span>
                          <span
                            className={`text-sm font-bold ${
                              playData.success_rate > 80
                                ? "text-green-600"
                                : playData.success_rate > 60
                                  ? "text-yellow-600"
                                  : "text-slate-600"
                            }`}
                          >
                            {playData.success_rate}%
                          </span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="bg-slate-50 px-6 py-4 border-t border-slate-200 flex items-center justify-between">
            <div className="flex items-center text-sm text-slate-500">
              <Clock className="h-4 w-4 mr-1" />
              Changes saved automatically
            </div>

            <div className="flex space-x-3">
              <button
                onClick={onClose}
                className="inline-flex items-center px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-md hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                disabled={!playData.play_name?.trim() || !playData.p_type}
                className="inline-flex items-center px-4 py-2 text-sm font-medium text-white bg-emerald-600 border border-transparent rounded-md hover:bg-emerald-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500 disabled:bg-slate-400 disabled:cursor-not-allowed"
              >
                <Save className="h-4 w-4 mr-2" />
                {initialPlay?.id ? "Update Play" : "Create Play"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
